from django.urls import path
from books.views import (
    books,
    book,
    author,
    delete_book,
    delete_publisher,
    delete_author,
    AuthorSearch,
    PublisherSearch,
    post_book,
    post_author,
    post_publisher,
    put_book,
    put_publisher,
    put_author,
    classification,
    register_user,
    login_user,
    logout_user,
)

urlpatterns = [
    path("books/", books, name="books"),
    path("book/<int:pk>/", book, name="book"),
    path("author/<int:pk>/", author, name="author"),
    path("search-author/", AuthorSearch.as_view(), name="search-author"),
    path("search-publisher/", PublisherSearch.as_view(), name="search-publisher"),
    path("classification/<int:pk>/", classification, name="classification"),
    path("post/book/", post_book, name="post-book"),
    path("post/publisher/", post_publisher, name="post-publisher"),
    path("post/author/", post_author, name="post-author"),
    path("delete/book/<int:pk>/", delete_book, name="delete-book"),
    path("delete/publisher/<int:pk>/", delete_publisher, name="delete-book"),
    path("delete/author/<int:pk>/", delete_author, name="delete-author"),
    path("put/book/<int:pk>/", put_book, name="put-book"),
    path("put/publisher/<int:pk>/", put_publisher, name="put-publisher"),
    path("put/author/<int:pk>/", put_author, name="put-author"),
    path("register/", register_user, name="register-user"),
    path("login/", login_user, name="login-user"),
    path("logout/", logout_user, name="logout-user"),
]
