from django.urls import path
from books.views import (
    books,
    book,
    author,
    BookDelete,
    PublisherDelete,
    AuthorDelete,
    AuthorSearch,
    PublisherSearch,
    BookPost,
    PublisherPost,
    AuthorPost,
    BookPut,
    PublisherPut,
    AuthorPut,
    classification,
    register_user,
    login_user,
    logout_user,
)

urlpatterns = [
    path("books/", books, name="books"),
    path("book/<int:pk>/", book, name="book"),
    path("author/<int:pk>/", author, name="author"),
    path("search-author/", AuthorSearch.as_view(), name="search-author"),
    path("search-publisher/", PublisherSearch.as_view(), name="search-publisher"),
    path("classification/<int:pk>/", classification, name="classification"),
    path("post/book/", BookPost.as_view(), name="post-book"),
    path("post/publisher/", PublisherPost.as_view(), name="post-publisher"),
    path("post/author/", AuthorPost.as_view(), name="post-author"),
    path("delete/book/<int:pk>/", BookDelete.as_view(), name="delete-book"),
    path("delete/publisher/<int:pk>/", PublisherDelete.as_view(), name="delete-book"),
    path("delete/author/<int:pk>/", AuthorDelete.as_view(), name="delete-author"),
    path("put/book/<int:pk>/", BookPut.as_view(), name="put-book"),
    path("put/publisher/<int:pk>/", PublisherPut.as_view(), name="put-publisher"),
    path("put/author/<int:pk>/", AuthorPut.as_view(), name="put-author"),
    path("register/", register_user, name="register-user"),
    path("login/", login_user, name="login-user"),
    path("logout/", logout_user, name="logout-user"),
]
